package clases;
// Generated 12-jun-2016 12:16:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Puntajes generated by hbm2java
 */
public class Puntajes  implements java.io.Serializable {


     private Integer idPuntaje;
     private int idUsuario;
     private int idTrivia;
     private double puntaje;
     private Date fecha;

    public Puntajes() {
    }

    public Puntajes(int idUsuario, int idTrivia, double puntaje, Date fecha) {
       this.idUsuario = idUsuario;
       this.idTrivia = idTrivia;
       this.puntaje = puntaje;
       this.fecha = fecha;
    }
   
    public Integer getIdPuntaje() {
        return this.idPuntaje;
    }
    
    public void setIdPuntaje(Integer idPuntaje) {
        this.idPuntaje = idPuntaje;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdTrivia() {
        return this.idTrivia;
    }
    
    public void setIdTrivia(int idTrivia) {
        this.idTrivia = idTrivia;
    }
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


