package clases;
// Generated 12-jun-2016 12:16:22 by Hibernate Tools 4.3.1



/**
 * Respuestas generated by hbm2java
 */
public class Respuestas  implements java.io.Serializable {


     private Integer idRespuesta;
     private int idPregunta;
     private String contestacion;

    public Respuestas() {
    }

    public Respuestas(int idPregunta, String contestacion) {
       this.idPregunta = idPregunta;
       this.contestacion = contestacion;
    }
   
    public Integer getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Integer idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getContestacion() {
        return this.contestacion;
    }
    
    public void setContestacion(String contestacion) {
        this.contestacion = contestacion;
    }




}


