package clases;
// Generated 12-jun-2016 12:16:22 by Hibernate Tools 4.3.1



/**
 * Trivias generated by hbm2java
 */
public class Trivias  implements java.io.Serializable {


     private Integer idTrivia;
     private String nombre;

    public Trivias() {
    }

    public Trivias(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdTrivia() {
        return this.idTrivia;
    }
    
    public void setIdTrivia(Integer idTrivia) {
        this.idTrivia = idTrivia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


